### ISSUE TITLE
Basic auth settings do not seem to generate a correct Gate config

### ISSUE THREAD

**Issue by atheriel** [ezimanyi/kleat#187]
I'm trying to set up basic auth for tools to interact with Gate without needing a heavier auth flow. Following the existing docs, I have

```yaml
security:
  authn:
    enabled: true
    basic:
      enabled: true
      user:                                                                                   
        username: basic-user
        password: basic-password
```

Running the latest `kleat` generates a `gate.yml` file with the following:

```yaml
security:                                                                                                                                     
  basic:                                                                                                                                      
    enabled: true                                                                                                                             
    user:                                                                                                                                     
      password: basic-user                                                                                                                 
      username: basic-password
```

However, Gate itself does not seem to accept this format; from the logs:

```
2021-09-29 18:24:54.449 ERROR 1 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  : 
The use of configuration keys that are no longer supported was found in the environment:

Property source 'applicationConfig: [file:/opt/spinnaker/config/gate.yml]':
        Key: security.basic.enabled
                Line: 3
                Reason: The security auto-configuration is no longer customizable.


Please refer to the migration guide or reference guide for potential alternatives.
```

From looking at Gate's [test suite](https://github.com/spinnaker/gate/blob/master/gate-web/src/test/resources/basic-auth.properties), it seems a basic auth setup might look more like

```yaml
security.basicform.enabled=true
spring.security.user.name=basic-user
spring.security.user.password=basic-password
```

and it's possible this changed at [`70024a3`](https://github.com/spinnaker/gate/commit/70024a326411d9cde215e7267dd1b713a4453760).

Am I correct in thinking that changes need to be made to `kleat` to support Gate's newer basic auth configuration format?
